### ISSUE TITLE
joint_p的问题

### ISSUE THREAD

**Issue by ShulinCao** [tyliupku/soft-label-RE#1]
您好，请问论文里A对每个relation type都设置了confidence，代码里为什么只有一个scalar一个joint_p?

**Comment by tyliupku** [comment]
非常抱歉！ 回复真的太晚了！
这边就是设置的所有的relation type的可信度都是相同的，
如再有问题可以邮件联系，谢谢！

**Comment by ShulinCao** [comment]
好的，谢谢！
