### ISSUE TITLE
关于训练集的问题

### ISSUE THREAD

**Issue by ZhixiuYe** [tyliupku/soft-label-RE#2]
你好，
我从你给的百度云链接下载了数据集，发现训练集的句子个数570088和论文中汇报的（522611）不一致，还有就是我发现这个训练集（570088）中存在和测试集中的entity pair重叠的部分，用这个作为训练集是不是不太合适？

**Comment by majingbit** [comment]
是的，我也发现作者在不同训练集上做的对比，对比算法在57w上效果也很好
